# Generated by Django 2.2.6 on 2019-11-16 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.FloatField()),
                ('investment_value', models.FloatField()),
                ('capital_asset', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_liability', models.FloatField()),
                ('non_current_liability', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SalesAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('deal_amount', models.IntegerField()),
                ('liberage', models.IntegerField()),
                ('net_amount', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sales.Product')),
                ('sales_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sales.Sale')),
            ],
        ),
        migrations.CreateModel(
            name='PayableAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('deal_amount', models.IntegerField()),
                ('liberage', models.IntegerField()),
                ('net_amount', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sales.Product')),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sales.Purchase')),
            ],
        ),
    ]
