# Generated by Django 2.2.6 on 2019-12-12 04:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('annual_return_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_levied', models.DecimalField(decimal_places=2, max_digits=12)),
                ('asset_value', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_levied', models.DecimalField(decimal_places=2, max_digits=12)),
                ('liability_type', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('annual_return_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('liability_value', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='ShareholderFunds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equity_share', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reserves_surplus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('revaluation_reserves', models.DecimalField(decimal_places=2, max_digits=12)),
                ('share_application_money', models.DecimalField(decimal_places=2, max_digits=12)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.FinancialYear')),
            ],
        ),
        migrations.CreateModel(
            name='SalesAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('price', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sales.Product')),
                ('sales_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sales.Sale')),
            ],
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_profit_before_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('real_profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.FinancialYear')),
            ],
        ),
        migrations.CreateModel(
            name='PayableAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sales.Product')),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sales.Purchase')),
            ],
        ),
        migrations.CreateModel(
            name='LiabilitySources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secured_loans', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unsecured_loans', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reserves_surplus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('revaluation_reserves', models.DecimalField(decimal_places=2, max_digits=12)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.FinancialYear')),
            ],
        ),
        migrations.CreateModel(
            name='FundApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_block', models.DecimalField(decimal_places=2, max_digits=12)),
                ('capital_work_in_progress', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inventories', models.DecimalField(decimal_places=2, max_digits=12)),
                ('debtors', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cash_and_bank_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loans_forwarded', models.DecimalField(decimal_places=2, max_digits=12)),
                ('operational_activities', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_of_materials', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change_in_inventories', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employee_benefit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('finance_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.FinancialYear')),
            ],
        ),
    ]
