# Generated by Django 2.2.6 on 2019-12-10 19:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payableaccount',
            old_name='deal_amount',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='payableaccount',
            name='liberage',
        ),
        migrations.RemoveField(
            model_name='payableaccount',
            name='net_amount',
        ),
        migrations.RemoveField(
            model_name='payableaccount',
            name='sales_id',
        ),
        migrations.RemoveField(
            model_name='salesaccount',
            name='purchase_id',
        ),
        migrations.AddField(
            model_name='payableaccount',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='payableaccount',
            name='purchase_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Sales.Purchase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesaccount',
            name='sales_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Sales.Sale'),
            preserve_default=False,
        ),
    ]
