# Generated by Django 2.2.6 on 2019-12-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20191211_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liability',
            name='current_liability',
        ),
        migrations.RemoveField(
            model_name='liability',
            name='non_current_liability',
        ),
        migrations.AddField(
            model_name='liability',
            name='annual_return_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liability',
            name='liability_type',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liability',
            name='liability_value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='liability',
            name='tax_levied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
