# Generated by Django 2.2.6 on 2019-12-11 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='user',
            new_name='by',
        ),
    ]
