# Generated by Django 2.0 on 2019-11-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_emailfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailfiles',
            name='file',
            field=models.FileField(upload_to='Media/email_departments/'),
        ),
    ]
