# Generated by Django 2.1.7 on 2019-10-16 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50)),
                ('dept', models.CharField(choices=[('C', 'CEO'), ('H', 'HR'), ('S', 'SALES'), ('A', 'ACCOUNTS')], max_length=100)),
                ('position', models.CharField(max_length=50, null=True)),
                ('date_of_joining', models.DateField(null=True)),
                ('is_verified', models.BooleanField()),
                ('is_complete', models.BooleanField()),
                ('cv', models.FileField(upload_to=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence', models.CharField(max_length=16)),
                ('validated', models.BooleanField()),
            ],
        ),
    ]
