# Generated by Django 2.2.6 on 2019-12-12 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70)),
                ('dept', models.CharField(choices=[('CEO', 'CEO'), ('HR', 'HR'), ('SALES', 'SALES'), ('ACCOUNTS', 'ACCOUNTS')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence', models.CharField(max_length=40)),
                ('validated', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=15, null=True)),
                ('date', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50, null=True)),
                ('dept', models.CharField(choices=[('CEO', 'CEO'), ('HR', 'HR'), ('SALES', 'SALES'), ('ACCOUNTS', 'ACCOUNTS')], max_length=100)),
                ('position', models.CharField(max_length=50, null=True)),
                ('date_of_joining', models.DateField(null=True)),
                ('is_verified', models.BooleanField()),
                ('is_complete', models.BooleanField()),
                ('cv', models.FileField(upload_to='Media/cv')),
                ('profile_pic', models.ImageField(upload_to='Media/profile_pics')),
                ('reporting_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.Employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
