# Generated by Django 2.1.7 on 2019-10-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='cv',
        ),
    ]
