# Generated by Django 2.2.6 on 2020-10-24 19:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201025_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='licence',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
