# Generated by Django 2.1.7 on 2019-10-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_employee_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cv',
            field=models.FileField(default=1, upload_to='Media/cv'),
            preserve_default=False,
        ),
    ]
