# Generated by Django 2.1.7 on 2019-10-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_employee_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_no',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
