# Generated by Django 2.1.7 on 2019-11-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20191031_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_pic',
            field=models.FileField(default=1, upload_to='Media/profile_pics'),
            preserve_default=False,
        ),
    ]
