# Generated by Django 2.1.7 on 2019-11-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_employee_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(upload_to='Media/profile_pics'),
        ),
    ]
