# Generated by Django 2.1.7 on 2019-11-04 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_auto_20191104_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='reporting_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.Employee'),
        ),
    ]
