# Generated by Django 2.1.7 on 2019-11-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_remove_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dept',
            field=models.CharField(choices=[('CEO', 'CEO'), ('HR', 'HR'), ('SALES', 'SALES'), ('ACCOUNTS', 'ACCOUNTS')], max_length=100),
        ),
    ]
